REFERENCE_TICKER: "SPY"
BATCH_SIZE: 20
MAX_WORKERS: 10  # Increased for performance
MAX_RETRIES: 7
INITIAL_DELAY: 5
START_DATE: "1998-12-01"
END_DATE: "2022-01-01"
MIN_PERCENTILE: 80
TRADING_DAYS_PER_MONTH: 20
MIN_TICKERS_PER_INDUSTRY: 2
EXIT_WAIT_FOR_ENTER: false
