name: Update RS Rankings

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install yfinance pandas requests tqdm pyyaml; fi

      - name: Run relative strength script
        run: python relative-strength.py true
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Push to rs-log repo
        env:
          RS_LOG_PAT: ${{ secrets.PAT }}
        run: |
          git clone https://dpatelj88:${{ secrets.PAT }}@github.com/dpatelj88/rs-log.git
          mkdir -p output
          [ "$(ls -A output)" ] || { echo "Output directory empty, creating fallback file"; echo "No output generated" > output/status.txt; }
          rsync -av --delete output/ rs-log/output/
          cd rs-log
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.csv
          git diff --staged --quiet || git commit -m "Update relative strength output files: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push || echo "Push failed, check PAT permissions or network"
        if: success() || failure()

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: '*.log'
          retention-days: 7

      - name: Upload output files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: |
            output/
            data/price_data.json
            data/failed_tickers.json
            data/failure_reasons.json
          retention-days: 7
