name: Update RS Rankings

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3  # Checkout the repository content to GitHub runner
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Updated to 3.11 for better support
      - name: Install dependencies and execute script
        run: |
          python -m pip install -r requirements.txt
          python relative-strength.py true || { echo "Script failed"; exit 1; }
      - name: Push RSRATING.csv to TradingView repo
        run: |
          git clone https://dpatelj88:${{ secrets.PAT }}@github.com/dpatelj88/tradingview-data.git
          [ -f ./output/RSRATING.csv ] || { echo "RSRATING.csv not found"; exit 1; }
          cp ./output/RSRATING.csv ./tradingview-data/data
          cd tradingview-data
          git config user.name "CI" && git config user.email "ci@github.com"
          git add --all
          git commit -m "CI RSRATING update" || echo "Nothing to commit"
          git push || echo "Nothing to push"
      - name: Push to rs-log repo
        run: |
          git clone https://dpatelj88:${{ secrets.PAT }}@github.com/dpatelj88/rs-log.git
          [ -d ./output ] && [ "$(ls -A ./output)" ] || { echo "Output directory empty"; exit 1; }
          rsync -av --delete ./output/ ./rs-log/output/
          cd rs-log
          git config user.name "CI" && git config user.email "ci@github.com"
          git add --all
          git commit -m "CI output update" || echo "Nothing to commit"
          git push || echo "Nothing to push"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: output/
