name: RS_Score
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install yfinance pandas requests tqdm pyyaml ratelimit retrying; fi
      - name: Run update_stocks.py
        run: python update_stocks.py
        env:
          PYTHONPATH: ${{ github.workspace }}
      - name: Run rs_data.py
        run: python rs_data.py
        env:
          PYTHONPATH: ${{ github.workspace }}
      - name: Run rs_ranking.py
        run: python rs_ranking.py true
        env:
          PYTHONPATH: ${{ github.workspace }}
      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p output data data_persist
          [ "$(ls -A data data_persist output)" ] || { echo "Output directories empty, creating fallback file"; echo "No output generated" > output/status.txt; }
          git add --all
          git diff --staged --quiet || git commit -m "Update relative strength output files: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push || echo "Push failed, check repository permissions or network"
      - uses: actions/upload-artifact@v4
        with:
          name: logs
          path: "*.log"
          retention-days: 7
          if-no-files-found: warn
      - uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: |
            output/*.csv
            data/price_data.json
            data/failed_tickers.json
            data/failure_reasons.json
            data_persist/ticker_info.json
          retention-days: 7
          if-no-files-found: warn
