name: update_stock_weekly_NASDAQ
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install yfinance pandas requests tqdm pyyaml ratelimit; fi
      - name: Run update_stocks.py
        run: |
          for i in {1..3}; do
            echo "Attempt $i..."
            python data_persist/update_stocks.py && break
            echo "Attempt $i failed. Retrying in 5 seconds..."
            sleep 5
          done
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/data_persist
      - name: Check ticker_info.json for SPY
        run: |
          jq '.SPY' data_persist/ticker_info.json || echo "SPY not found in ticker_info.json"
      - name: Run rs_data.py
        run: |
          for i in {1..3}; do
            echo "Attempt $i..."
            python rs_data.py && break
            echo "Attempt $i failed. Retrying in 5 seconds..."
            sleep 5
          done
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/data_persist
      - name: Run rs_ranking.py
        run: |
          for i in {1..3}; do
            echo "Attempt $i..."
            python rs_ranking.py true && break
            echo "Attempt $i failed. Retrying in 5 seconds..."
            sleep 5
          done
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/data_persist
      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p output data data_persist
          [ "$(ls -A data data_persist output)" ] || { echo "Output directories empty, creating fallback file"; echo "No output generated" > output/status.txt; }
          git add data/*.json data_persist/*.json data_persist/*.txt output/*.csv
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update relative strength output files: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push origin main
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: logs
          path: "*.log"
          retention-days: 7
          if-no-files-found: warn
      - uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: |
            output/*.csv
            data/*.json
            data_persist/*.json
            data_persist/*.txt
          retention-days: 7
          if-no-files-found: warn
